from typing import Optional

_RULES: list[tuple[str, str]] = [
    ("netflix", "Subscriptions"),
    ("spotify", "Subscriptions"),
    ("hulu", "Subscriptions"),
    ("disney+", "Subscriptions"),
    ("disney plus", "Subscriptions"),
    ("amazon prime", "Subscriptions"),
    ("apple.com/bill", "Subscriptions"),
    ("google one", "Subscriptions"),
    ("youtube premium", "Subscriptions"),
    ("starbucks", "Food & Dining"),
    ("mcdonald", "Food & Dining"),
    ("chipotle", "Food & Dining"),
    ("doordash", "Food & Dining"),
    ("uber eats", "Food & Dining"),
    ("grubhub", "Food & Dining"),
    ("chick-fil-a", "Food & Dining"),
    ("subway", "Food & Dining"),
    ("domino", "Food & Dining"),
    ("pizza hut", "Food & Dining"),
    ("taco bell", "Food & Dining"),
    ("panera", "Food & Dining"),
    ("dunkin", "Food & Dining"),
    ("walmart", "Groceries"),
    ("whole foods", "Groceries"),
    ("kroger", "Groceries"),
    ("trader joe", "Groceries"),
    ("aldi", "Groceries"),
    ("publix", "Groceries"),
    ("safeway", "Groceries"),
    ("wegmans", "Groceries"),
    ("sam's club", "Groceries"),
    ("shell", "Gas & Fuel"),
    ("chevron", "Gas & Fuel"),
    ("exxon", "Gas & Fuel"),
    ("mobil", "Gas & Fuel"),
    ("speedway", "Gas & Fuel"),
    ("circle k", "Gas & Fuel"),
    ("amazon", "Shopping"),
    ("target", "Shopping"),
    ("best buy", "Shopping"),
    ("ebay", "Shopping"),
    ("etsy", "Shopping"),
    ("home depot", "Shopping"),
    ("lowe's", "Shopping"),
    ("ikea", "Shopping"),
    ("tj maxx", "Shopping"),
    ("marshalls", "Shopping"),
    ("cvs", "Healthcare"),
    ("walgreens", "Healthcare"),
    ("rite aid", "Healthcare"),
    ("pharmacy", "Healthcare"),
    ("at&t", "Utilities"),
    ("verizon", "Utilities"),
    ("t-mobile", "Utilities"),
    ("comcast", "Utilities"),
    ("xfinity", "Utilities"),
    ("spectrum", "Utilities"),
    ("pg&e", "Utilities"),
    ("duke energy", "Utilities"),
    ("con edison", "Utilities"),
    ("amc", "Entertainment"),
    ("ticketmaster", "Entertainment"),
    ("steam", "Entertainment"),
    ("playstation", "Entertainment"),
    ("xbox", "Entertainment"),
    ("nintendo", "Entertainment"),
    ("uber", "Travel"),
    ("lyft", "Travel"),
    ("airbnb", "Travel"),
    ("delta", "Travel"),
    ("united airlines", "Travel"),
    ("american airlines", "Travel"),
    ("southwest", "Travel"),
    ("marriott", "Travel"),
    ("hilton", "Travel"),
]


def categorize(description: str) -> Optional[str]:
    """Return a category for the merchant description, or None if unmatched."""
    lower = description.lower()
    for keyword, category in _RULES:
        if keyword in lower:
            return category
    return None
