from typing import Optional

_RULES: list[tuple[str, str]] = [
    # Credit card payments — must be first so they don't match gas/utility keywords
    ("payment thank you", "Other"),
    ("autopay", "Other"),
    ("online payment", "Other"),
    ("netflix", "Subscriptions"),
    ("spotify", "Subscriptions"),
    ("hulu", "Subscriptions"),
    ("disney+", "Subscriptions"),
    ("disney plus", "Subscriptions"),
    ("amazon prime", "Subscriptions"),
    ("apple.com/bill", "Subscriptions"),
    ("google one", "Subscriptions"),
    ("youtube premium", "Subscriptions"),
    ("starbucks", "Food & Dining"),
    ("mcdonald", "Food & Dining"),
    ("chipotle", "Food & Dining"),
    ("doordash", "Food & Dining"),
    ("uber eats", "Food & Dining"),
    ("grubhub", "Food & Dining"),
    ("chick-fil-a", "Food & Dining"),
    ("subway", "Food & Dining"),
    ("domino", "Food & Dining"),
    ("pizza hut", "Food & Dining"),
    ("taco bell", "Food & Dining"),
    ("panera", "Food & Dining"),
    ("dunkin", "Food & Dining"),
    ("wendy", "Food & Dining"),
    ("popeyes", "Food & Dining"),
    ("popeye", "Food & Dining"),
    ("churchs chick", "Food & Dining"),
    ("church's chick", "Food & Dining"),
    ("burger king", "Food & Dining"),
    ("whataburger", "Food & Dining"),
    ("jack in the box", "Food & Dining"),
    ("sonic drive", "Food & Dining"),
    ("dairy queen", "Food & Dining"),
    ("five guys", "Food & Dining"),
    ("arby", "Food & Dining"),
    ("raising cane", "Food & Dining"),
    ("wingstop", "Food & Dining"),
    ("zaxby", "Food & Dining"),
    ("culver", "Food & Dining"),
    ("ihop", "Food & Dining"),
    ("denny", "Food & Dining"),
    ("waffle house", "Food & Dining"),
    ("olive garden", "Food & Dining"),
    ("applebee", "Food & Dining"),
    ("chilis", "Food & Dining"),
    ("red lobster", "Food & Dining"),
    ("buffalo wild", "Food & Dining"),
    ("little caesar", "Food & Dining"),
    ("papa john", "Food & Dining"),
    ("jersey mike", "Food & Dining"),
    ("jimmy john", "Food & Dining"),
    ("firehouse sub", "Food & Dining"),
    ("walmart", "Groceries"),
    ("whole foods", "Groceries"),
    ("kroger", "Groceries"),
    ("trader joe", "Groceries"),
    ("aldi", "Groceries"),
    ("publix", "Groceries"),
    ("safeway", "Groceries"),
    ("wegmans", "Groceries"),
    ("sam's club", "Groceries"),
    ("shell", "Gas & Fuel"),
    ("chevron", "Gas & Fuel"),
    ("exxon", "Gas & Fuel"),
    ("mobil", "Gas & Fuel"),
    ("speedway", "Gas & Fuel"),
    ("circle k", "Gas & Fuel"),
    ("amazon", "Shopping"),
    ("target", "Shopping"),
    ("best buy", "Shopping"),
    ("ebay", "Shopping"),
    ("etsy", "Shopping"),
    ("home depot", "Shopping"),
    ("lowe's", "Shopping"),
    ("ikea", "Shopping"),
    ("tj maxx", "Shopping"),
    ("marshalls", "Shopping"),
    ("cvs", "Healthcare"),
    ("walgreens", "Healthcare"),
    ("rite aid", "Healthcare"),
    ("pharmacy", "Healthcare"),
    ("at&t", "Utilities"),
    ("verizon", "Utilities"),
    ("t-mobile", "Utilities"),
    ("comcast", "Utilities"),
    ("xfinity", "Utilities"),
    ("spectrum", "Utilities"),
    ("pg&e", "Utilities"),
    ("duke energy", "Utilities"),
    ("con edison", "Utilities"),
    ("amc", "Entertainment"),
    ("ticketmaster", "Entertainment"),
    ("steam", "Entertainment"),
    ("playstation", "Entertainment"),
    ("xbox", "Entertainment"),
    ("nintendo", "Entertainment"),
    ("uber", "Travel"),
    ("lyft", "Travel"),
    ("airbnb", "Travel"),
    ("delta", "Travel"),
    ("united airlines", "Travel"),
    ("american airlines", "Travel"),
    ("southwest", "Travel"),
    ("marriott", "Travel"),
    ("hilton", "Travel"),
]


def categorize(description: str) -> Optional[str]:
    """Return a category for the merchant description, or None if unmatched."""
    lower = description.lower()
    for keyword, category in _RULES:
        if keyword in lower:
            return category
    return None
